language: python
python:
  - "3.5"
  - "3.6"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile

script:
  - pipenv run lint
  - pipenv run test
